### ISSUE TITLE
取出来的时候转换失败了

### ISSUE THREAD

**Issue by Zhouioi** [yangwenjie88/delay-queue#4]
ScoredSortedItem{delayTime=15, delayQueueJodId=11223344} 在redis里的数据是这样的

取出来就报string 不能转ScoredSortedItem类

直接下载你的项目运行的，是redis版本的问题吗？我的是3.0的

**Comment by yangwenjie88** [comment]
最好把错误堆栈信息贴出来，从你描述的看可能是序列化转换的问题，redission是保存对象的，手工给redis设置的字符串是不行，后面有时间搞一个jedis版本的

**Comment by Zhouioi** [comment]
感谢回复。
报错：java.lang.ClassCastException: java.lang.String cannot be cast to com.mobuz.rest.service.delayqueue.core.ScoredSortedItem
项目什么都没有改，直接调用添加接口然后就报错了
